import { describe, expect, it, vi } from 'vitest';
import { buildHttpLiveFfmpegArgs } from '../electron/tapo/httpStream';
import { buildRtspHlsOutputOptions } from '../electron/tapo/streamHelpers';

vi.mock('electron', () => {
  return {
    app: {
      isPackaged: true,
      getAppPath: vi.fn().mockReturnValue('/mocked/app/path'),
    },
  };
});

// The -hls_segment_filename value is built with path.join, so its separators
// differ by OS. Normalise to forward slashes so the snapshots are stable on
// both Windows (dev) and Linux (CI).
const fwd = (args: string[]): string[] => args.map((a) => a.replace(/\\/g, '/'));

describe('buildHttpLiveFfmpegArgs', () => {
  it('builds args with pcma (alaw) audio', () => {
    expect(
      fwd(
        buildHttpLiveFfmpegArgs({
          audioCodec: 'pcma',
          audioRate: 8000,
          segDir: '/seg',
          sessionToken: 'tok',
          m3u8: '/seg/stream-tok.m3u8',
        }),
      ),
    ).toMatchInlineSnapshot(`
      [
        "-loglevel",
        "warning",
        "-fflags",
        "+genpts+discardcorrupt",
        "-err_detect",
        "ignore_err",
        "-analyzeduration",
        "2000000",
        "-probesize",
        "1000000",
        "-f",
        "mpegts",
        "-i",
        "pipe:0",
        "-analyzeduration",
        "0",
        "-probesize",
        "32",
        "-f",
        "alaw",
        "-ar",
        "8000",
        "-ac",
        "1",
        "-i",
        "pipe:3",
        "-map",
        "0:v:0?",
        "-c:v",
        "libx264",
        "-preset",
        "veryfast",
        "-tune",
        "zerolatency",
        "-pix_fmt",
        "yuv420p",
        "-force_key_frames",
        "expr:gte(t,n_forced*1)",
        "-sc_threshold",
        "0",
        "-map",
        "1:a:0",
        "-af",
        "aresample=async=1:first_pts=0",
        "-c:a",
        "aac",
        "-ac",
        "1",
        "-ar",
        "44100",
        "-b:a",
        "128k",
        "-max_interleave_delta",
        "0",
        "-muxpreload",
        "0",
        "-muxdelay",
        "0",
        "-f",
        "hls",
        "-hls_time",
        "1",
        "-hls_list_size",
        "5",
        "-hls_flags",
        "delete_segments+independent_segments",
        "-hls_segment_filename",
        "/seg/segment-tok-%03d.ts",
        "/seg/stream-tok.m3u8",
      ]
    `);
  });

  it('builds args with pcmu (mulaw) audio', () => {
    expect(
      fwd(
        buildHttpLiveFfmpegArgs({
          audioCodec: 'pcmu',
          audioRate: 16000,
          segDir: '/seg',
          sessionToken: 'tok',
          m3u8: '/seg/stream-tok.m3u8',
        }),
      ),
    ).toMatchInlineSnapshot(`
      [
        "-loglevel",
        "warning",
        "-fflags",
        "+genpts+discardcorrupt",
        "-err_detect",
        "ignore_err",
        "-analyzeduration",
        "2000000",
        "-probesize",
        "1000000",
        "-f",
        "mpegts",
        "-i",
        "pipe:0",
        "-analyzeduration",
        "0",
        "-probesize",
        "32",
        "-f",
        "mulaw",
        "-ar",
        "16000",
        "-ac",
        "1",
        "-i",
        "pipe:3",
        "-map",
        "0:v:0?",
        "-c:v",
        "libx264",
        "-preset",
        "veryfast",
        "-tune",
        "zerolatency",
        "-pix_fmt",
        "yuv420p",
        "-force_key_frames",
        "expr:gte(t,n_forced*1)",
        "-sc_threshold",
        "0",
        "-map",
        "1:a:0",
        "-af",
        "aresample=async=1:first_pts=0",
        "-c:a",
        "aac",
        "-ac",
        "1",
        "-ar",
        "44100",
        "-b:a",
        "128k",
        "-max_interleave_delta",
        "0",
        "-muxpreload",
        "0",
        "-muxdelay",
        "0",
        "-f",
        "hls",
        "-hls_time",
        "1",
        "-hls_list_size",
        "5",
        "-hls_flags",
        "delete_segments+independent_segments",
        "-hls_segment_filename",
        "/seg/segment-tok-%03d.ts",
        "/seg/stream-tok.m3u8",
      ]
    `);
  });

  it('builds video-only args when no audio codec is detected', () => {
    expect(
      fwd(
        buildHttpLiveFfmpegArgs({
          audioCodec: undefined,
          audioRate: 8000,
          segDir: '/seg',
          sessionToken: 'tok',
          m3u8: '/seg/stream-tok.m3u8',
        }),
      ),
    ).toMatchInlineSnapshot(`
      [
        "-loglevel",
        "warning",
        "-fflags",
        "+genpts+discardcorrupt",
        "-err_detect",
        "ignore_err",
        "-analyzeduration",
        "2000000",
        "-probesize",
        "1000000",
        "-f",
        "mpegts",
        "-i",
        "pipe:0",
        "-map",
        "0:v:0?",
        "-c:v",
        "libx264",
        "-preset",
        "veryfast",
        "-tune",
        "zerolatency",
        "-pix_fmt",
        "yuv420p",
        "-force_key_frames",
        "expr:gte(t,n_forced*1)",
        "-sc_threshold",
        "0",
        "-max_interleave_delta",
        "0",
        "-muxpreload",
        "0",
        "-muxdelay",
        "0",
        "-f",
        "hls",
        "-hls_time",
        "1",
        "-hls_list_size",
        "5",
        "-hls_flags",
        "delete_segments+independent_segments",
        "-hls_segment_filename",
        "/seg/segment-tok-%03d.ts",
        "/seg/stream-tok.m3u8",
      ]
    `);
  });
});

describe('buildRtspHlsOutputOptions', () => {
  it('builds the output options with a session token', () => {
    expect(fwd(buildRtspHlsOutputOptions('/seg', 'tok'))).toMatchInlineSnapshot(`
      [
        "-map",
        "0:v:0",
        "-map",
        "0:a:0?",
        "-c:v",
        "libx264",
        "-preset",
        "veryfast",
        "-tune",
        "zerolatency",
        "-pix_fmt",
        "yuv420p",
        "-force_key_frames",
        "expr:gte(t,n_forced*1)",
        "-sc_threshold",
        "0",
        "-c:a",
        "aac",
        "-af",
        "aresample=async=1:first_pts=0",
        "-ac",
        "1",
        "-ar",
        "44100",
        "-b:a",
        "128k",
        "-max_interleave_delta",
        "0",
        "-muxpreload",
        "0",
        "-muxdelay",
        "0",
        "-f",
        "hls",
        "-hls_time",
        "1",
        "-hls_list_size",
        "5",
        "-hls_flags",
        "delete_segments+independent_segments",
        "-hls_segment_filename",
        "/seg/segment-tok-%03d.ts",
      ]
    `);
  });

  it('falls back to the "live" segment token when none is provided', () => {
    expect(fwd(buildRtspHlsOutputOptions('/seg'))).toMatchInlineSnapshot(`
      [
        "-map",
        "0:v:0",
        "-map",
        "0:a:0?",
        "-c:v",
        "libx264",
        "-preset",
        "veryfast",
        "-tune",
        "zerolatency",
        "-pix_fmt",
        "yuv420p",
        "-force_key_frames",
        "expr:gte(t,n_forced*1)",
        "-sc_threshold",
        "0",
        "-c:a",
        "aac",
        "-af",
        "aresample=async=1:first_pts=0",
        "-ac",
        "1",
        "-ar",
        "44100",
        "-b:a",
        "128k",
        "-max_interleave_delta",
        "0",
        "-muxpreload",
        "0",
        "-muxdelay",
        "0",
        "-f",
        "hls",
        "-hls_time",
        "1",
        "-hls_list_size",
        "5",
        "-hls_flags",
        "delete_segments+independent_segments",
        "-hls_segment_filename",
        "/seg/segment-live-%03d.ts",
      ]
    `);
  });
});
